### PR TITLE
Add loop option in track to loop through out the entire timeline if true

### PR DESCRIPTION
**Pull request by vasinl124**
I want to be able to loop a selected track the entire timeline

### CODE REVIEW

**Comment by faroit** [comment]
@vasinl124 I wont have time to review this. But just from a high level perspective: this PR implements looping across the whole track. 

* does this respect the cursor position?
* would it make sense to so include start-stop position in the loop api?

**Comment by vasinl124** [comment]
Nope, I just use `source.loop = true;`. I know this is ugly and dirty but it's ok for my use case(I just want to export the audio offline)

**Comment by odaymusic** [comment]
how to add effects ?https://alemangui.github.io/pizzicato/#reverb

**Comment by naomiaro** [comment]
Sorry for closing, but this has diverged a bit and might not work properly.

**Pull request closed without merging**
