### PR TITLE
Fix travis

### PR DESCRIPTION
**Pull request by faroit**
update travis config according to [docs](https://docs.travis-ci.com/user/gui-and-headless-browsers/)

### CODE REVIEW

**Comment by faroit** [comment]
this should be merged before #107

**Comment by naomiaro** [comment]
thanks for this!

**Comment by naomiaro** [comment]
ah this PR had the same commit in it as the other PR so it merged both. Will have to fix that in a bit.

**Comment by faroit** [comment]
oopsie, yes. I manually reverted it. sorry

**Comment by faroit** [comment]
@naomiaro could you manage to incorporate #107? It would be great to have a new npm release asap since I want to use the fixed version is production

**Comment by naomiaro** [comment]
I've found that this causes issues with the annotations. Going to have to find a fix for that.

**Pull request merged**
