### PR TITLE
Soundtouchjs support for pitch & tempo

### LINKED ISSUE #19: Alter playback speed?
After a few teething problems due to my lack of experience, now enjoying building some multitracks with this! I teach a Brazilian style of music called choro and you can see the tracks I've built up below.

http://chorotest.hol.es/

Is there a way to implement the webaudio playback speed feature, using a global slider like the master volume control. Then my students could speed up or slow down the track slightly (within reason).

https://developer.mozilla.org/en-US/Apps/Fundamentals/Audio_and_video_delivery/WebAudio_playbackRate_explained

### PR DESCRIPTION
**Pull request by naomiaro**
- integrate https://www.npmjs.com/package/soundtouchjs
- close #19

### CODE REVIEW

**Comment by sanbaideng** [comment]
speed up is a  good feature，thanks，

**Comment by p-himik** [comment]
@naomiaro If I understand correctly, the commit has been completely reverted. Was there something wrong with `soundtouchjs` that made its use unfeasible?

**Comment by naomiaro** [comment]
@p-himik It's limited to work with only one track that I saw at the moment.

**Comment by p-himik** [comment]
Oh... but at least it sounds like we can have a pitch shifter per track with all pitch shifters not being a part of the API and being controlled in a centralized manner from `Playlist`. Would you consider a PR like that?

**Comment by naomiaro** [comment]
The timing would drift with this library, it doesn't support time synced shifting of more than one track. A change to soundtouch js would have to be done itself.

**Pull request merged**
